org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C:\\src\\jdk-21
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.jvm.target.validation.mode=warning
kotlin.compiler.execution.strategy=in-process
systemProp.http.keepAlive=false
org.gradle.vfs.watch=false
android.suppressUnsupportedCompileSdk=36